### PR TITLE
fix: memory leaks

### LINKED ISSUE #63: Memory leaks
I looked at the code and noticed strong reference cycles:
```swift
    /// Lazy initialized `QueryAPI`.
    public lazy var queryAPI: QueryAPI = {
        QueryAPI(client: self)
    }()

    /// Lazy initialized `DeleteAPI`.
    public lazy var deleteAPI: DeleteAPI = {
        DeleteAPI(client: self)
    }()

    /// Lazy initialized `InvokableScriptsAPI`.
    public lazy var invokableScriptsApi: InvokableScriptsAPI = {
        InvokableScriptsAPI(client: self)
    }()
```
and inside QueryAPI, DeleteAPI, InvokableScriptsAPI:
```swift
    /// Shared client.
    private let client: InfluxDBClient
```
So QueryAPI, DeleteAPI, InvokableScriptsAPI have a strong reference to the client and the client has strong references to them, creating a reference cycle that leads to a memory leak. None of these objects can be deinitialized. 
Since none of these classes store anything mutable, I suggest using structs instead of classes here and making these properties computed:
```swift
    public var queryAPI: QueryAPI {
        QueryAPI(client: self)
    }

    public var deleteAPI: DeleteAPI {
        DeleteAPI(client: self)
    }

    public var invokableScriptsApi: InvokableScriptsAPI {
        InvokableScriptsAPI(client: self)
    }
```
`InfluxDBClient` could also be a struct, and it would be ideal if all these types conformed to the `Sendable` protocol.

### LINKED ISSUE #65: PointSettings init is internal
InfluxDBClient.PointSettings.init() is internal and can not be accessed outside of the library

### PR DESCRIPTION
**Pull request by dankinsoid**
Closes #63
Closes #65 

## Proposed Changes

- Replace classes with structs and lazy vars with computed vars

## Checklist

- [x] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] A test has been added if appropriate
- [x] `swift test` completes successfully
- [x] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

### CODE REVIEW

**Review by bednar — CHANGES_REQUESTED** [review]
Thanks again for your PR 👍 

Can you please satisfy our Checklist:

image

**Review by bednar — CHANGES_REQUESTED** [review]
Could you please ensure that our CI checks are satisfied as well?

image

**Review by bednar — APPROVED** [review]
Hi @dankinsoid,

Thank you very much for your Pull Request. It appears that the final check is failing due to flakiness of the tests on the macOS platform. However, we're still able to merge your PR regardless, as from my point of view, it looks perfectly fine!

If you have any other contributions or suggestions, please don't hesitate to share them. We greatly appreciate your efforts.

Best Regards.

**Comment by dankinsoid** [comment]
@bednar Hello! Do I need to do smth to merge the PR? I need it for [my library](https://github.com/dankinsoid/swift-influxdb-telemetry)

**Comment by bednar** [comment]
Thanks again for your PR 👍. I will merge at Monday and after that we will release new version of the client.

**Comment by bednar** [comment]
Hi @dankinsoid,

I wanted to give you an update on the progress we're making with your Pull Request. I've prepared PR #66 to address some CI checks issues we've been facing. Once PR #66 is reviewed and merged, we will be able to proceed with merging your PR as well.

As mentioned yesterday, we are on track to release the new version of the client, which will include your fix, by the end of this week.

Thank you for your patience and your contributions. I'll keep you updated as we move forward.

Best regards

**Comment by dankinsoid** [comment]
@bednar thank you!

**Pull request merged**
